# sudo: required
language: node_js
dist: bionic
node_js:
  - 'lts/*'

# uses default install and script configuration:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# install:
  # - npm ci
# script:
  # - npm test

### TODO: deploy