language: node_js
dist: bionic
node_js:
  - lts/*

before_install:
  - cp inMemoryDB_EWFlex.default.json inMemoryDB_EWFlex.json

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh -oStrictHostKeyChecking=no $EVD_WEB_HOST 'bash ./deploy.sh'
  on:
    branch: ocn-bridge-component

env:
  global:
    secure: Ey+t+7AWTUXWkJGgTl80sKLU4ueQ0FFF0kIQLFgGCL0uMcnVEXgoTzW3bylcVKqxPBp3maStK6DFFWN0CzlkzFFUetCASolJOMNymLxCdXs5hYpp+ZQ3sAd4mId4Ic0lJqqcd5lMTwFo8t/aYvyZ0h9A3fEBXvevIjDtY/NnUot096l0WO5n/jEx42vnwKFSLbJv6BGSqNQWWnkCAO0yZ1e4P32tIB9mdkoqIwQN7d0NQshMiDiAiciTMXsh7dXSSbA1rnRvpIoJ8r0+OypoXw4qkT3BcGJMa8LMJozcxts1hQGq3wEr9wm0U/F7DUBmvN/2eK/hHxQjwqqpIR06i4s4Kh+PbtmM/hdm205ixe56aZ1lQnk3e0Ui8fM0IFNtKjvykylJLXeFfDm6YDc+aPoDf/nE/VP024XTQpAAOBVoQBzgenpniS0Q1i5QNz9diln3anuOGJkXy//vCXfClMm2KuY/K95NKQHMqdpkaOYkWiNZGu2Th9zw5tCwa1kvxCmLCT2lQHyXtLBKWrArMUw2KZK7f7y5xZ8WXbZ/vnD5GiMcj8Gmt4FhJfzfctmPa6TSa5TjNRzKoZHvSBtM6ww4yFUH3erMGcpDkxBH3BRfTMZ+oyFs2kjPEPrlLENDdYD504sA8neUmOeI9LW+k8M2GDY7rcpubPP3OhFc1ZM=
