# Check out https://hub.docker.com/_/node to select a new base image
FROM node:10-slim

# Some dependencies from package.json are installed from git
RUN apt-get update && apt-get upgrade -y && apt-get install -y git python3 build-essential build-essential

# Use the same uid and gid as the host to avoid permission errors
ARG UID
ARG GID
RUN usermod -u $UID node
RUN groupmod -g $GID node
# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node entrypoint.sh ./

ENTRYPOINT ["sh", "entrypoint.sh"]
CMD ["install_and_start"]
